/**
 * Created by twi18192 on 19/11/15.
 */

var appConstants = {
    GATENODE_CHANGEPOSITION: "GATENODE_CHANGEPOSITION",
    DRAGGED_ELEMENTID: "DRAGGED_ELEMENTID",
    DRAGGED_ELEMENT: "DRAGGED_ELEMENT",
    CHANGE_NODEPOSITION: "CHANGE_NODEPOSITION",

    SELECT_NODE: "SELECT_NODE",
    DESELECT_ALLNODES: "DESELECT_ALLNODES",
    //CHANGE_GATE1STYLING: "CHANGE_GATE1STYLING"
};

module.exports = appConstants;