/**
 * Created by twi18192 on 19/11/15.
 */

var appConstants = {
    GATENODE_CHANGEPOSITION: "GATENODE_CHANGEPOSITION",
    DRAGGED_ELEMENT: "DRAGGED_ELEMENT",
    CHANGE_NODEPOSITION: "CHANGE_NODEPOSITION"
};

module.exports = appConstants;